[package]
name = "pscontroller-rs"
version = "0.1.0"
authors = ["edwinamsler"]

[dependencies]
embedded-hal = "0.1.2"
#linux-embedded-hal = "0.1.1"
linux-embedded-hal = { path = "../linux-embedded-hal" }
spidev = "0.3.0"
bit_reverse = "0.1.7"
bitflags = "1.0"

